
Isso pode estar bem errado!! REVISAR, ENTENDER

```{r}
estatistica_observada <- salario_tempo |>
  specify(explanatory = ano_salario, 
                 response = valor_salario) |>
   hypothesise(null = "independence") |> 
  calculate(stat =  "F")

estatistica_observada
```

```{r}
distribuicao_hipotese_nula <- salario_tempo |>
  specify(explanatory = ano_salario, 
                 response = valor_salario) |>
  assume(distribution = "F")

distribuicao_hipotese_nula
```

```{r}
distribuicao_hipotese_nula  |> 
  visualize() + 
  shade_p_value(estatistica_observada,
                direction = "greater")
```

```{r}
valor_p <- distribuicao_hipotese_nula  |> 
  get_p_value(obs_stat = estatistica_observada,
              direction = "greater")

valor_p
```

---

```{r}
# Calculando a estatística F
estatistica_observada <- dados |> 
  specify(response = IDADE, explanatory = ORIGEM)  |> 
  hypothesize(null = "independence")  |> 
  calculate(stat = "F")

# gerando uma distribuição p/ hipótese nula
null_dist <- dados  |> 
  specify(response = IDADE, explanatory = ORIGEM)  |> 
  hypothesize(null = "independence")  |> 
  generate(reps = 1000, type = "permute")  |> 
  calculate(stat = "F")


# visualizando o p_valor encontrado
null_dist  |> 
  visualize() + 
  shade_p_value(estatistica_observada,
                direction = "greater")


valor_p <- null_dist  |> 
  get_p_value(obs_stat = estatistica_observada,
              direction = "greater")

valor_p

```
