<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Beatriz Milz">
<title>Prova 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
</head>
<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Índice</h2>
   
  <ul>
<li><a href="#informa%C3%A7%C3%B5es-sobre-a-prova" id="toc-informações-sobre-a-prova" class="nav-link active" data-scroll-target="#informa%C3%A7%C3%B5es-sobre-a-prova">Informações sobre a prova</a></li>
  <li>
<a href="#quest%C3%B5es-de-1-a-5" id="toc-questões-de-1-a-5" class="nav-link" data-scroll-target="#quest%C3%B5es-de-1-a-5">Questões de 1 a 5</a>
  <ul class="collapse">
<li><a href="#quest%C3%A3o-1" id="toc-questão-1" class="nav-link" data-scroll-target="#quest%C3%A3o-1">Questão 1</a></li>
  <li><a href="#quest%C3%A3o-2" id="toc-questão-2" class="nav-link" data-scroll-target="#quest%C3%A3o-2">Questão 2</a></li>
  <li><a href="#quest%C3%A3o-3" id="toc-questão-3" class="nav-link" data-scroll-target="#quest%C3%A3o-3">Questão 3</a></li>
  <li><a href="#quest%C3%A3o-4" id="toc-questão-4" class="nav-link" data-scroll-target="#quest%C3%A3o-4">Questão 4</a></li>
  <li><a href="#quest%C3%A3o-5" id="toc-questão-5" class="nav-link" data-scroll-target="#quest%C3%A3o-5">Questão 5</a></li>
  </ul>
</li>
  <li>
<a href="#quest%C3%B5es-6-e-7" id="toc-questões-6-e-7" class="nav-link" data-scroll-target="#quest%C3%B5es-6-e-7">Questões 6 e 7</a>
  <ul class="collapse">
<li><a href="#quest%C3%A3o-6" id="toc-questão-6" class="nav-link" data-scroll-target="#quest%C3%A3o-6">Questão 6</a></li>
  <li><a href="#quest%C3%A3o-7" id="toc-questão-7" class="nav-link" data-scroll-target="#quest%C3%A3o-7">Questão 7</a></li>
  </ul>
</li>
  <li>
<a href="#quest%C3%B5es-8-a-10" id="toc-questões-8-a-10" class="nav-link" data-scroll-target="#quest%C3%B5es-8-a-10">Questões 8 a 10</a>
  <ul class="collapse">
<li><a href="#quest%C3%A3o-8" id="toc-questão-8" class="nav-link" data-scroll-target="#quest%C3%A3o-8">Questão 8</a></li>
  <li><a href="#quest%C3%A3o-9" id="toc-questão-9" class="nav-link" data-scroll-target="#quest%C3%A3o-9">Questão 9</a></li>
  <li><a href="#quest%C3%A3o-10" id="toc-questão-10" class="nav-link" data-scroll-target="#quest%C3%A3o-10">Questão 10</a></li>
  </ul>
</li>
  <li>
<a href="#quest%C3%B5es-de-11-a-14" id="toc-questões-de-11-a-14" class="nav-link" data-scroll-target="#quest%C3%B5es-de-11-a-14">Questões de 11 a 14</a>
  <ul class="collapse">
<li><a href="#quest%C3%A3o-11" id="toc-questão-11" class="nav-link" data-scroll-target="#quest%C3%A3o-11">Questão 11</a></li>
  <li><a href="#quest%C3%A3o-12" id="toc-questão-12" class="nav-link" data-scroll-target="#quest%C3%A3o-12">Questão 12</a></li>
  <li><a href="#quest%C3%A3o-13" id="toc-questão-13" class="nav-link" data-scroll-target="#quest%C3%A3o-13">Questão 13</a></li>
  <li><a href="#quest%C3%A3o-14" id="toc-questão-14" class="nav-link" data-scroll-target="#quest%C3%A3o-14">Questão 14</a></li>
  </ul>
</li>
  <li>
<a href="#quest%C3%B5es-15-a-20" id="toc-questões-15-a-20" class="nav-link" data-scroll-target="#quest%C3%B5es-15-a-20">Questões 15 a 20</a>
  <ul class="collapse">
<li><a href="#quest%C3%A3o-15" id="toc-questão-15" class="nav-link" data-scroll-target="#quest%C3%A3o-15">Questão 15</a></li>
  <li><a href="#quest%C3%A3o-16" id="toc-questão-16" class="nav-link" data-scroll-target="#quest%C3%A3o-16">Questão 16</a></li>
  <li><a href="#quest%C3%A3o-17" id="toc-questão-17" class="nav-link" data-scroll-target="#quest%C3%A3o-17">Questão 17</a></li>
  <li><a href="#quest%C3%A3o-18" id="toc-questão-18" class="nav-link" data-scroll-target="#quest%C3%A3o-18">Questão 18</a></li>
  <li><a href="#quest%C3%A3o-19" id="toc-questão-19" class="nav-link" data-scroll-target="#quest%C3%A3o-19">Questão 19</a></li>
  <li>
<a href="#quest%C3%A3o-20" id="toc-questão-20" class="nav-link" data-scroll-target="#quest%C3%A3o-20">Questão 20</a>
  <ul class="collapse">
<li><a href="#a-estudo-transversal" id="toc-a-estudo-transversal" class="nav-link" data-scroll-target="#a-estudo-transversal">A) Estudo transversal</a></li>
  <li><a href="#b-estudo-caso-controle" id="toc-b-estudo-caso-controle" class="nav-link" data-scroll-target="#b-estudo-caso-controle">B) Estudo Caso-controle</a></li>
  <li><a href="#c-coorte" id="toc-c-coorte" class="nav-link" data-scroll-target="#c-coorte">C) Coorte</a></li>
  <li><a href="#resposta" id="toc-resposta" class="nav-link" data-scroll-target="#resposta">Resposta</a></li>
  </ul>
</li>
  </ul>
</li>
  <li><a href="#links-que-podem-ser-%C3%BAteis" id="toc-links-que-podem-ser-úteis" class="nav-link" data-scroll-target="#links-que-podem-ser-%C3%BAteis">Links que podem ser úteis:</a></li>
  </ul></nav>
</div>
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Prova 1</h1>
<p class="subtitle lead">Estatística aplicada à psicobiologia I</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Beatriz Milz </p>
          </div>
  </div>
    
  
    
  </div>
  


</header><div class="cell">
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/options.html">options</a></span><span class="op">(</span>scipen <span class="op">=</span> <span class="fl">9999</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="informações-sobre-a-prova" class="level2"><h2 class="anchored" data-anchor-id="informações-sobre-a-prova">Informações sobre a prova</h2>
<p>Para cada questão, selecione o teste estatístico correto, as Variáveis Dependentes e Independentes caso existam e faça um parágrafo descrevendo os resultados encontrados com as notações específicas e também destacando aonde está a diferença significante, caso ela exista.</p>
<p>Para todas as análises, adote nível de significancia de 5%</p>
</section><section id="questões-de-1-a-5" class="level1"><h1>Questões de 1 a 5</h1>
<p>Os dados abaixo representam os Tempos Totais de Sono de 100 pacientes, declarado pelo paciente e medido por um teste real, chamado polissonografia.</p>
<p>O objetivo era verificar se pacientes sem depressão (50) ou com depressão (50) têm uma boa percepção em relação ao tempo que de fato permanecem dormindo. NÃO É PARA FAZER CONTA ALGUMA, UTILIZE AS INFORMAÇÕES DA TABELA ABAIXO!</p>
<p><img src="images/clipboard-792303048.png" class="img-fluid"></p>
<section id="questão-1" class="level2"><h2 class="anchored" data-anchor-id="questão-1">Questão 1</h2>
<p><strong>1 - Existe diferença estatística entre os grupos com depressão e sem depressão em função do tempo de sono dito pelo paciente?</strong></p>
<p>Variável independente: Grupo (variável categórica, com 2 categorias: com depressão/sem depressão).</p>
<p>Variável dependente: TTS dito pelo paciente (em minutos, variável numérica). Essa variável tem distribuição próxima à normal segundo o teste de Shapiro-Wilk, mas não apresenta homogeneidade das variâncias segundo o teste de Levenne.</p>
<p>O teste escolhido foi o teste t independente. Nesse caso, é importante realizar a correção de Welch devido à não-homogeneidade das variâncias.</p>
<p>A estatística T encontrada foi de 1,11, sendo menor que o valor crítico (T=1,22) para considerar o valor p &lt; 0.05. Portanto, não temos evidências para apontar que existe diferença estatística entre os grupos (depressão/sem depressão) em função do tempo de sono real medido para os pacientes.</p>
</section><section id="questão-2" class="level2"><h2 class="anchored" data-anchor-id="questão-2">Questão 2</h2>
<p><strong>2 - Existe diferença estatística entre os grupos com depressão e sem depressão em função do tempo de sono real medido pela polissonografia?</strong></p>
<p>Variável independente: Grupo (variável categórica, com 2 categorias: com depressão/sem depressão).</p>
<p>Variável dependente: TTS real (em minutos, variável numérica). Essa variável tem distribuição próxima à normal segundo o teste de Shapiro-Wilk, e apresenta homogeneidade das variâncias segundo o teste de Levenne.</p>
<p>O teste escolhido foi o teste t independente.</p>
<p>A estatística T encontrada foi de 6,28, sendo maior que o valor crítico (T=1,22) para considerar o valor p &lt; 0.05. Portanto, existe diferença estatística entre os grupos (depressão/sem depressão) em função do tempo de sono real medido para os pacientes.</p>
</section><section id="questão-3" class="level2"><h2 class="anchored" data-anchor-id="questão-3">Questão 3</h2>
<p><strong>3 - Existe diferença estatística entre o tempo de sono dito pelo paciente e o tempo de sono real para as pessoas com depressão?</strong></p>
<p>Variável independente: categoria de TTS (variável categórica, com 2 categorias: TTS dito pelo paciente/TTS real).</p>
<p>Variável dependente: tempo em minutos (em minutos, variável numérica).</p>
<p>Neste caso, consideramos apenas o grupo de pessoas com depressão, e utilizamos um teste-t pareado.</p>
<p>Como se trata de um teste de medidas repetidas, é importante checar a esfericidade, o que pode ser verificado com o teste de Mauchly. Como não temos a informação considerando apenas para pessoas com depressão, considerei o valor total, que apresentou esfericidade (p = 0,61).</p>
<p>O resultado obtido foi T=7,22, sendo maior que o valor crítico (T=3,96) para considerar o valor p &lt; 0.05.</p>
<p>Portanto, para as pessoas com depressão, existe diferença estatística entre o tempo de sono dito pelo paciente e o tempo de sono real para os pacientes com depressão.</p>
</section><section id="questão-4" class="level2"><h2 class="anchored" data-anchor-id="questão-4">Questão 4</h2>
<p><strong>4 - Existe diferença estatística entre o tempo de sono dito pelo paciente e o tempo de sono real para as pessoas sem depressão?</strong></p>
<p>Variável independente: categoria de TTS (variável categórica, com 2 categorias: TTS dito pelo paciente/TTS real).</p>
<p>Variável dependente: tempo em minutos (em minutos, variável numérica).</p>
<p>Neste caso, consideramos apenas o grupo de pessoas sem depressão, e utilizamos um teste-t pareado.</p>
<p>Como se trata de um teste de medidas repetidas, é importante checar a esfericidade, o que pode ser verificado com o teste de Mauchly. Como não temos a informação considerando apenas para pessoas sem depressão, considerei o valor total, que apresentou esfericidade (p = 0,61).</p>
<p>O resultado obtido foi T=3,09, sendo menor que o valor crítico (T=3,96) para considerar o valor p &lt; 0.05.</p>
<p>Portanto, para as pessoas com depressão, não existe diferença estatística entre o tempo de sono dito pelo paciente e o tempo de sono real para os pacientes com depressão.</p>
</section><section id="questão-5" class="level2"><h2 class="anchored" data-anchor-id="questão-5">Questão 5</h2>
<p><strong>5 - Supondo que pessoas em geral costumam dormir em média 8 horas por noite (480 minutos), podemos dizer que toda nossa amostra (independentemente da presença de depressão ou não) possui valor médio <em>semelhante</em> de tempo total de sono real em relação a média esperada populacional?</strong></p>
<ul>
<li><p>Média amostral = 460,4</p></li>
<li><p>Média populacional = 480</p></li>
</ul>
<p>Vou calcular o intervalo de confiança da média amostral:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">media_amostral_tts_sr</span> <span class="op">&lt;-</span> <span class="fl">460.4</span></span>
<span><span class="va">dp_amostral_tts_sr</span> <span class="op">&lt;-</span> <span class="fl">18.4</span></span>
<span><span class="va">n_amostral_tts_sr</span> <span class="op">&lt;-</span> <span class="fl">100</span></span>
<span></span>
<span><span class="va">z</span> <span class="op">&lt;-</span> <span class="fl">1.96</span> <span class="co"># para nível de significancia 5%</span></span>
<span></span>
<span><span class="va">ic_incompleto</span> <span class="op">&lt;-</span> <span class="va">z</span> <span class="op">*</span> <span class="op">(</span><span class="va">dp_amostral_tts_sr</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">n_amostral_tts_sr</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ic_tts_sr</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">media_amostral_tts_sr</span> <span class="op">-</span> <span class="va">ic_incompleto</span>,</span>
<span>    <span class="va">media_amostral_tts_sr</span> <span class="op">+</span> <span class="va">ic_incompleto</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">tab_media</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="fu">::</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span></span>
<span>  media <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">460.4</span>, <span class="fl">480</span><span class="op">)</span>,</span>
<span>  tipo <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"amostral"</span>, <span class="st">"populacional"</span><span class="op">)</span>,</span>
<span>  media_min <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">ic_tts_sr</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="cn">NA</span><span class="op">)</span>,</span>
<span>  media_max <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">ic_tts_sr</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>, <span class="cn">NA</span><span class="op">)</span>,  </span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">tab_media</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: right;">media</th>
<th style="text-align: left;">tipo</th>
<th style="text-align: right;">media_min</th>
<th style="text-align: right;">media_max</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">460.4</td>
<td style="text-align: left;">amostral</td>
<td style="text-align: right;">456.7936</td>
<td style="text-align: right;">464.0064</td>
</tr>
<tr class="even">
<td style="text-align: right;">480.0</td>
<td style="text-align: left;">populacional</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">tab_media</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">tipo</span>, y <span class="op">=</span> <span class="va">media</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_errorbar</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>ymin <span class="op">=</span> <span class="va">media_min</span>, ymax <span class="op">=</span> <span class="va">media_max</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_y_continuous</a></span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">450</span>, <span class="fl">500</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Outra opção: Teste-t para uma amostra? O professor disse para não fazer conta alguma.</p>
</div>
</div>
</div>
<p><strong>Podemos dizer que toda nossa amostra (independentemente da presença de depressão ou não) possui valor médio semelhante de tempo total de sono real em relação a média esperada populacional?</strong></p>
<ul>
<li><p>Não é semelhante</p></li>
<li><p>A amostra possui valor médio de <strong>sono menor</strong> do que a média populacional</p></li>
<li><p>p-valor?</p></li>
</ul>
<p><strong>Alternativas</strong>:</p>
<ul>
<li><p>Sim com p menor que 5%. A amostra possui valor médio de sono semelhante a média populacional</p></li>
<li><p>Sim com p maior que 5%. A amostra possui valor médio de sono maior do que a média populacional</p></li>
<li><p><label><input type="checkbox" checked=""><strong>Não</strong> com p menor que 5% A amostra possui valor médio de <strong>sono menor</strong> do que a média populacional</label></p></li>
<li><p><label><input type="checkbox"><strong>Não</strong> com p maior que 5%. A amostra possui valor médio de <strong>sono menor</strong> do que a média populacional</label></p></li>
<li><p>Não com p maior que 5%. A amostra possui valor médio de sono semelhante a média populacional</p></li>
<li><p>Sim com p maior que 5%. A amostra possui valor médio de sono menor do que a média populacional</p></li>
<li><p>Não temos informações suficientes</p></li>
</ul></section></section><section id="questões-6-e-7" class="level1"><h1>Questões 6 e 7</h1>
<p>Uma empresa farmaceutica chamada OH desenvolveu um novo produto voltado para redução da azia. O departamento de pesquisa dessa marca resolveu fazer uma coleta de dados para verificar aeficácia percebida na redução da azia. O estudo foi feito e isso motivou a inclusão de uma frase no rótulo do produto, a saber: <strong>“Antiácido: Reduz a Azia em 93%*”</strong>. Na parte de trás do rótulo temos uma informação que é relacionado com o asterisco apresentado no slogan <strong>Resultado com base em uma pesquisa de percepção de uso com 16 voluntários</strong>. Com base nas informações acima, responda as perguntas 6 e 7 abaixo:</p>
<section id="questão-6" class="level2"><h2 class="anchored" data-anchor-id="questão-6">Questão 6</h2>
<p><strong>6 - Calcule o intervalo em torno da proporção de pessoas que relataram ter sua azia reduzida com 99% de confiança (z=3). Podemos dizer que este resultado encontrado (93%) é fidedigno e reprodutível?</strong></p>
<p>Vamos calcular o intervalo de confiança para proporções:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">n_pesquisa_antiacido</span> <span class="op">=</span> <span class="fl">16</span></span>
<span><span class="va">z</span> <span class="op">=</span> <span class="fl">3</span> <span class="co"># 99% de confiança</span></span>
<span><span class="va">prop_encontrada_pesquisa_antiacido</span> <span class="op">=</span> <span class="fl">0.93</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># p * (1-p)</span></span>
<span><span class="va">parte_1</span> <span class="op">&lt;-</span> <span class="va">prop_encontrada_pesquisa_antiacido</span><span class="op">*</span><span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">prop_encontrada_pesquisa_antiacido</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># p * (1-p)/n</span></span>
<span><span class="va">parte_2</span> <span class="op">&lt;-</span> <span class="va">parte_1</span><span class="op">/</span><span class="va">n_pesquisa_antiacido</span></span>
<span></span>
<span><span class="co"># sqrt(p * (1-p)/n)</span></span>
<span><span class="va">parte_3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">parte_2</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># z * sqrt(p * (1-p)/n)</span></span>
<span><span class="va">parte_4</span> <span class="op">&lt;-</span> <span class="va">z</span> <span class="op">*</span> <span class="va">parte_3</span></span>
<span></span>
<span><span class="va">ic_pesquisa_antiacido</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">prop_encontrada_pesquisa_antiacido</span><span class="op">-</span><span class="va">parte_4</span>, <span class="va">prop_encontrada_pesquisa_antiacido</span><span class="op">+</span><span class="va">parte_4</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">ic_pesquisa_antiacido</span><span class="op">*</span><span class="fl">100</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1]  74 112</code></pre>
</div>
</div>
<p>O Intervalo de confiança encontrado foi entre 74% e 112%.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="op">(</span><span class="va">ic_pesquisa_antiacido</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">-</span><span class="va">ic_pesquisa_antiacido</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">)</span><span class="op">*</span><span class="fl">100</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 38</code></pre>
</div>
</div>
<p>Faixa de erro: 38%. Muito erro!!!</p>
<ul>
<li><p>O que 112% de proporção significa? Não faz sentido ter proporção maior que 100%?</p></li>
<li><p>O que o professor quer dizer com resultado fidedigno e reprodutível? Acredito que dependa do erro aceitável. Isso não está escrito na questão.</p></li>
</ul>
<p><strong>Alternativas</strong>:</p>
<ul>
<li><p>O resultado 93% - IC95% [74-112%] é fidedigno e reprodutível com base no Intervalo de Confiança</p></li>
<li><p>O resultado 93% - IC95% [74-112%] não é fidedigno e reprodutível com base no Intervalo de Confiança</p></li>
<li><p><label><input type="checkbox">O resultado 93% - <strong>IC99%</strong> [74-110%] é fidedigno e reprodutível com base no Intervalo de Confiança</label></p></li>
<li><p><label><input type="checkbox">O resultado 93% - <strong>IC99%</strong> [74-110%] não é fidedigno e reprodutível com base no Intervalo de Confiança</label></p></li>
<li><p>O resultado 93% - IC95% [74-100%] é fidedigno e reprodutível com base no Intervalo de Confiança</p></li>
<li><p><label><input type="checkbox" checked="">O resultado 93% - <strong>IC99%</strong> [74-100%] não é fidedigno e reprodutível com base no Intervalo de Confiança</label></p></li>
<li><p>O resultado 93% - IC67% [74-100%] é fidedigno e reprodutível com base no Intervalo de Confiança</p></li>
</ul></section><section id="questão-7" class="level2"><h2 class="anchored" data-anchor-id="questão-7">Questão 7</h2>
<p><strong>7- Caso a empresa faça uma nova pesquisa onde foi encontrada a mesma proporção de pessoas com redução de caspa conforme o rótulo, com o mesmo nível de significancia de 99%, erro total esperado máximo de 1%, calcule qual seria o tamanho de amostra necessário para este novo estudo?</strong></p>
<div class="cell">
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># n_caspa = ?</span></span>
<span><span class="va">z</span> <span class="op">=</span> <span class="fl">3</span> <span class="co"># 99% de confiança</span></span>
<span><span class="va">prop_reducao_caspa</span> <span class="op">=</span> <span class="fl">0.93</span></span>
<span><span class="va">erro_total_max</span> <span class="op">=</span> <span class="fl">0.01</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Segundo anotações do caderno: n = z^2 * DP^2 / erro^2</p>
<p>Consideramos que DP = sqrt(p * (1-p))</p>
<div class="cell">
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">DP_caspa</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">prop_reducao_caspa</span> <span class="op">*</span> <span class="op">(</span><span class="fl">1</span><span class="op">-</span><span class="va">prop_reducao_caspa</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Calculando o n:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">n_caspa</span> <span class="op">=</span> <span class="op">(</span><span class="op">(</span><span class="va">z</span> <span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">*</span> <span class="op">(</span><span class="va">DP_caspa</span> <span class="op">^</span><span class="fl">2</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="op">(</span><span class="va">erro_total_max</span> <span class="op">^</span> <span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="va">n_caspa</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 5859</code></pre>
</div>
</div>
<p>Respondi: 5859</p>
</section></section><section id="questões-8-a-10" class="level1"><h1>Questões 8 a 10</h1>
<section id="questão-8" class="level2"><h2 class="anchored" data-anchor-id="questão-8">Questão 8</h2>
<p><strong>8- A figura abaixo representa 3 formas (A - boxplot, B - histograma, C - dotplot) de descrever o mesmo conjunto de dados (N=30). Existe diferença na interpretação dos dados por meio da análise de diferentes gráficos, mesmo utilizando os mesmos dados? Faça uma descrição detalhada das limitações e vantagens de cada apresentação gráfica:</strong></p>
<p><img src="images/clipboard-437422152.png" class="img-fluid"></p>
<p>As três representações permitem obter informações da distribuição dessa variável (chamada aqui de conjunto de dados):</p>
<ul>
<li><p>Boxplot: É uma forma mais sintética de ver a distribuição dos dados, permitindo ver a mediana e quartis.</p></li>
<li><p>Histograma: Apresenta a distribuição dos dados com mais detalhes que o Boxplot, porém representados em faixas. Não apresenta medidas como mediana e quartis.</p></li>
<li><p>Dotplot: Apresenta todos os valores do conjunto de dados. Não apresenta medidas como mediana e quartis.</p></li>
</ul>
<p>Existe diferença na interpretação dos gráficos:</p>
<p>A - O boxplot possibilita visualizar os quartis da variável. Conseguimos ver que a mediana da variável é próxima de 25.</p>
<p>B - O histograma possibilita visualizar a distribuição da variável. Conseguimos ver que a maior frequência dos valores estão entre 15 e 20. É possível ver que a distribuição tem dois pontos de concentração dos dados.</p>
<p>C - O dotplot permite ver cada um dos valores do conjunto de dados, e permite ver a concentração de dados entre os valores 10 e 20. É possível ver que a distribuição tem dois pontos de concentração dos dados.</p>
</section><section id="questão-9" class="level2"><h2 class="anchored" data-anchor-id="questão-9">Questão 9</h2>
<p><strong>9- O gráfico abaixo mostra 3 grupos de dados com tamanhos de amostra diferentes (3, 10 e 30, respectivamente). Responda qual a opção CORRETA.</strong></p>
<p><img src="images/clipboard-939251875.png" class="img-fluid"></p>
<p><strong>Alternativas:</strong></p>
<ul>
<li><p>A barra de amplitude sempre pode excluir valores individuais. FALSO: A amplitude é calculada a partir dos valores mínimo e máximo.</p></li>
<li><p>Podemos ter médias semelhantes para grupos com tamanhos de amostra diferentes, mas o desvio padrão é diferente dependendo do tamanho da amostra. FALSO: creio que o problema é o final da frase. O desvio padrão pode ser diferente, mas não necessariamente.</p></li>
<li><p>Quanto maior o tamanho da amostra, maior é o desvio padrão, independentemente do valor do tamanho da amostra. FALSO: podemos ter uma variável que mesmo com grande n apresenta um baixo desvio padrão, se ela tiver pouca variabilidade.</p></li>
<li><p>Gráficos de barra são os melhores para mostrar a variabilidade entre grupos em relação a gráficos como boxplot. FALSO: Os gráficos de barra não representam bem a variabilidade.</p></li>
<li><p>Intervalo de confiança não leva em conta o tamanho da amostra em seu cálculo. FALSO: utilizamos o n para calcular o IC.</p></li>
<li><p><label><input type="checkbox" checked="">Todas estão erradas</label></p></li>
</ul></section><section id="questão-10" class="level2"><h2 class="anchored" data-anchor-id="questão-10">Questão 10</h2>
<p>O gráfico acima mostra dados de dois grupos apresentados como um gráfico de barras (a esquerda). Além disso, foram simuladas 4 tipos de distribuição diferentes dos supostos dados e apresentados como gráficos de pontos (grupos simétricos, com outlier em um dos grupos, com amostras bimodais e com N desiguais). Logo abaixo são apresentados dados referentes a testes t independentes realizados em cada uma das condições, tendo os valores de p apresentados.</p>
<p><img src="images/clipboard-1542198701.png" class="img-fluid"></p>
<p><strong>10 - Com base na figura e nas informações acima, diga qual a alternativa CORRETA:</strong></p>
<ul class="task-list">
<li><p><label><input type="checkbox">Os resultados do teste t refletem que os valores de p são semelhantes, independente da distribuição ou do tamanho da amostra entre os grupos</label></p></li>
<li><p><label><input type="checkbox">Amostras bimodais geram vieses nos resultados do teste t</label></p></li>
<li><p><label><input type="checkbox">Podemos representar amostras com distribuições diferentes apenas usando gráficos de barra</label></p></li>
<li><p><label><input type="checkbox" checked="">Amostras com tamanhos desiguais podem gerar vieses nos resultados do teste t.</label></p></li>
<li><p><label><input type="checkbox">Todas estão corretas</label></p></li>
</ul></section></section><section id="questões-de-11-a-14" class="level1"><h1>Questões de 11 a 14</h1>
<p>Em um estudo foram avaliadas 30 crianças, sendo 15 de escolas públicas e 15 de escolas particulares. Todas elas foram submetidas a um teste de memória em dois momentos (antes e depois de um treino de motricidade). Os dados abaixo mostram os resultados das crianças em função do número de palavras lembradas.</p>
<p>NÃO É PARA FAZER CONTA ALGUMA, UTILIZE AS INFORMAÇÕES DA TABELA ABAIXO!</p>
<p><img src="images/clipboard-2288418485.png" class="img-fluid"></p>
<section id="questão-11" class="level2"><h2 class="anchored" data-anchor-id="questão-11">Questão 11</h2>
<p><strong>11 - Existe diferença entre Escolas Públicas e Privadas na média de palavras lembradas antes do treino de motricidade?</strong></p>
<p>A variável independente é o tipo de escola (pública/privada). Portanto é uma variável categórica, com 2 categorias.</p>
<p>A variável dependente é a quantidade de palavras lembradas antes do treino de motrocidade. Essa variável apresenta distribuição próxima à normal (baseado nos resultados do teste Shapiro-Wilk, p = 0.77), porém não apresenta homogeneidade das variâncias (baseado nos resultados do teste de Levenne, p = 0.01).</p>
<p>Podemos usar o teste-t independente, um teste paramétrico. Nesse caso, é importante realizar a correção de Welch devido à não-homogeneidade das variâncias.</p>
<p>Os resultados do teste-t independente (t = 6,87) apontam que existe diferença entre os grupos (escola pública e escola privada) na média de palavras lembradas antes do treino de motrocidade.</p>
</section><section id="questão-12" class="level2"><h2 class="anchored" data-anchor-id="questão-12">Questão 12</h2>
<p><strong>12 - Existe diferença entre Escolas Públicas e Privadas na média de palavras lembradas depois do treino de motricidade?</strong></p>
<p>A variável independente é o tipo de escola (pública/privada). Portanto é uma variável categórica, com 2 categorias.</p>
<p>A variável dependente é a quantidade de palavras lembradas depois do treino de motrocidade. Essa variável apresenta distribuição próxima à normal (baseado nos resultados do teste Shapiro-Wilk, p = 0.81), e apresenta homogeneidade das variâncias (baseado nos resultados do teste de Levenne, p = 0.30).</p>
<p>Podemos usar o teste t-independente, um teste paramétrico.</p>
<p>Os resultados do teste t independente (T = 5,59) apontam que existe diferença entre os grupos (escola pública e escola privada) na média de palavras lembradas depois do treino de motrocidade.</p>
</section><section id="questão-13" class="level2"><h2 class="anchored" data-anchor-id="questão-13">Questão 13</h2>
<p><strong>13 - Existe diferença entre o número de palavras lembradas antes e depois do treino para a Escola Privada?</strong></p>
<p>A variável independente é o tempo: antes ou depois do treino. Portanto é uma variável categórica, com 2 categorias.</p>
<p>A variável dependente é a quantidade de palavras lembradas.</p>
<p>Considerando apenas as crianças de escola privada:</p>
<p>Podemos usar o teste t-pareado.</p>
<p>Como se trata de um teste de medidas repetidas, é importante checar a esfericidade, o que pode ser verificado com o teste de Mauchly. Como não temos a informação considerando apenas para crianças de escolas privadas, considerei o valor total, que apresentou esfericidade (p = 0,61).</p>
<p>Os resultados do teste t pareado (T = 4,98) apontam que existe diferença entre os tempos (antes e depois do treino) na média de palavras lembradas pelas crianças.</p>
</section><section id="questão-14" class="level2"><h2 class="anchored" data-anchor-id="questão-14">Questão 14</h2>
<p><strong>14 - Existe diferença entre o número de palavras lembradas antes e depois do treino para a Escola Pública?</strong></p>
<p>A variável independente é o tempo: antes ou depois do treino. Portanto é uma variável categórica, com 2 categorias.</p>
<p>A variável dependente é a quantidade de palavras lembradas.</p>
<p>Considerando apenas as crianças de escola pública:</p>
<p>Podemos usar o teste t-pareado.</p>
<p>Como se trata de um teste de medidas repetidas, é importante checar a esfericidade, o que pode ser verificado com o teste de Mauchly. Como não temos a informação considerando apenas para crianças de escolas públicas, considerei o valor total, que apresentou esfericidade (p = 0,61).</p>
<p>Os resultados do teste t pareado (T = 3,59) apontam que não existe diferença entre os tempos (antes e depois do treino) na média de palavras lembradas pelas crianças.</p>
</section></section><section id="questões-15-a-20" class="level1"><h1>Questões 15 a 20</h1>
<section id="questão-15" class="level2"><h2 class="anchored" data-anchor-id="questão-15">Questão 15</h2>
<p>O Banco de dados para responder a questão abaixo pode ser encontrado aqui: <a href="https://bit.ly/2XC89jN" class="uri">https://bit.ly/2XC89jN</a></p>
<div class="cell">
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dados_hipertensao</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_delim</a></span><span class="op">(</span><span class="st">"Hipertensao.csv"</span>, </span>
<span>    delim <span class="op">=</span> <span class="st">";"</span>, escape_double <span class="op">=</span> <span class="cn">FALSE</span>, trim_ws <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">dados_hipertensao</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Rows: 18
Columns: 4
$ PACIENTE  &lt;chr&gt; "P1", "P2", "P3", "P4", "P5", "P6", "P7", "P8", "P9", "P10",…
$ `DROGA A` &lt;dbl&gt; 187, 182, 191, 174, 168, 168, 182, 180, 170, 171, 164, 159, …
$ `DROGA B` &lt;dbl&gt; 189, 191, 193, 180, 179, 194, 182, 178, 192, 190, 186, 183, …
$ `DROGA C` &lt;dbl&gt; 180, 185, 173, 174, 165, 175, 175, 174, 180, 175, 178, 180, …</code></pre>
</div>
</div>
<div class="cell">
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">hipertensao</span> <span class="op">&lt;-</span> <span class="va">dados_hipertensao</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">janitor</span><span class="fu">::</span><span class="fu"><a href="https://sfirke.github.io/janitor/reference/clean_names.html">clean_names</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">tidyr</span><span class="fu">::</span><span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span><span class="op">(</span>cols <span class="op">=</span> <span class="op">-</span><span class="va">paciente</span>, names_to <span class="op">=</span> <span class="st">"droga"</span>, values_to <span class="op">=</span> <span class="st">"pressao_arterial"</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="images/clipboard-885151021.png" class="img-fluid"></p>
<p><strong>15- Faça as análises estatísticas que julgar necessárias para verificar qual é o melhor tratamento. Faça um texto com as suas análises passo a passo e escreva sua conclusão como o faria para submeter um artigo para publicação. ESCREVA UM PARÁGRAFO DE ANÁLISE ESTATÍSTICA (Como na seção de métodos de um artigo) ONDE DEVEM SER APRESENTADAS - Qual a pergunta de pesquisa, VD e VI, Hipótese Nula e Alternativa e os testes estatísticos adotados e seus pré-requisitos caso seja necessário. ALÉM DISSO ESCREVA OUTRO PARÁGRAFO COM A ANÁLISE DOS DADOS - Resultados, notação dos testes, onde estão as diferenças entre os grupos/medidas e tamanhos do efeito. Utilize esse exercício como um treino para escrever seus próprios resultados daqui pra frente! Utilize o banco de dados apresentado no link acima. Fique a vontade para adicionar mais variáveis caso ache necessário</strong></p>
<div class="cell">
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">hipertensao</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 54 × 3
   paciente droga   pressao_arterial
   &lt;chr&gt;    &lt;chr&gt;              &lt;dbl&gt;
 1 P1       droga_a              187
 2 P1       droga_b              189
 3 P1       droga_c              180
 4 P2       droga_a              182
 5 P2       droga_b              191
 6 P2       droga_c              185
 7 P3       droga_a              191
 8 P3       droga_b              193
 9 P3       droga_c              173
10 P4       droga_a              174
# ℹ 44 more rows</code></pre>
</div>
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">hipertensao</span><span class="op">$</span><span class="va">pressao_arterial</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 159</code></pre>
</div>
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">hipertensao</span><span class="op">$</span><span class="va">pressao_arterial</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 194</code></pre>
</div>
</div>
<div class="cell">
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test</a></span><span class="op">(</span><span class="va">hipertensao</span><span class="op">$</span><span class="va">pressao_arterial</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  hipertensao$pressao_arterial
W = 0.97791, p-value = 0.5819</code></pre>
</div>
</div>
<div class="cell">
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">car</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/car/man/leveneTest.html">leveneTest</a></span><span class="op">(</span><span class="va">hipertensao</span><span class="op">$</span><span class="va">pressao_arterial</span> <span class="op">~</span> <span class="va">hipertensao</span><span class="op">$</span><span class="va">droga</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value  Pr(&gt;F)  
group  2  2.6326 0.08463 .
      39                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">hipertensao</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">pressao_arterial</span>, y <span class="op">=</span> <span class="va">droga</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"blue"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="index_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">pressao_arterial</span> <span class="op">~</span> <span class="va">droga</span>, data <span class="op">=</span> <span class="va">hipertensao</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  term         df sumsq meansq statistic   p.value
  &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 droga         2  869.  434.       8.31  0.000988
2 Residuals    39 2040.   52.3     NA    NA       </code></pre>
</div>
</div>
<ul>
<li><strong>Materiais e métodos: Análise estatística</strong></li>
</ul>
<p>Nesta pesquisa, buscamos responder a seguinte pergunta: Qual medicamento (droga A, B ou C) apresenta o melhor tratamento para a hipertensão (ou seja, apresenta maior diminuição de pressão arterial)?</p>
<p>A variável independente é a droga utilizada para o tratamento (droga A, B ou C). É uma variável categórica nominal.</p>
<p>A variável dependente é a pressão arterial, uma variável numérica discreta, apresentando valores entre 159 e 194.</p>
<p>A hipótese nula é de que a média da pressão arterial (Mpa) para a droga A é igual à Mpa para a droga B, e igual para a Mpa para a droga C:</p>
<p><code>Mpa_drogaA = Mpa_drogaB = Mpa_drogaC</code></p>
<p>A hipótese alternativa é de que as médias da pressão arterial são diferente entre os grupos:</p>
<p><code>Mpa_drogaA != Mpa_drogaB != Mpa_drogaC</code></p>
<p>O teste de Shapiro-Wilk foi utilizado para testar a normalidade da variável dependente (pressão arterial). O resultado apontou para a normalidade da variável (p-valor = 0.58).</p>
<p>O teste de Levenne foi utilizado para testar se existe homogeneidade das variâncias para a variável dependente. O resultado apontou que existe homogeneidade das variâncias (p-valor = 0.08).</p>
<p>Portanto, teste estatístico escolhido foi a ANOVA (análise de variância).</p>
<p>As análises de dados foram realizas utilizando o software R (R Core Team, 2024), e os seguintes pacotes: stats (R Core Team, 2024), car (Fox &amp; Weisberg, 2019), tidyverse (Wickham et al., 2019).</p>
<ul>
<li><strong>Resultados: Análise dos dados</strong></li>
</ul>
<p>A análise de variância apresentou F = 8.3, com p-valor &lt; 0.05, o que aponta que existe uma diferença significativa entre os grupos.</p>
<p>Para encontrar quais são os grupos com diferenças significativas, foi realizado um teste post-hoc:</p>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>TAMANHO DE EFEITO??? VER O FINAL DA AULA QUE FALTA!</p>
</div>
</div>
</div>
<ul>
<li><strong>Referências</strong></li>
</ul>
<p>Fox J, Weisberg S (2019). <em>An R Companion to Applied Regression</em>, Third edition. Sage, Thousand Oaks CA. <a href="https://socialsciences.mcmaster.ca/jfox/Books/Companion/" class="uri">https://socialsciences.mcmaster.ca/jfox/Books/Companion/</a>.</p>
<p>R Core Team (2024). <em>R: A Language and Environment for Statistical Computing</em>. R Foundation for Statistical Computing, Vienna, Austria. <a href="https://www.R-project.org/" class="uri">https://www.R-project.org/</a>.</p>
<p>Wickham H, Averick M, Bryan J, Chang W, McGowan LD, François R, Grolemund G, Hayes A, Henry L, Hester J, Kuhn M, Pedersen TL, Miller E, Bache SM, Müller K, Ooms J, Robinson D, Seidel DP, Spinu V, Takahashi K, Vaughan D, Wilke C, Woo K, Yutani H (2019). “Welcome to the tidyverse.” <em>Journal of Open Source Software</em>, <em>4</em>(43), 1686. doi:10.21105/joss.01686 <a href="https://doi.org/10.21105/joss.01686" class="uri">https://doi.org/10.21105/joss.01686</a>.</p>
</section><section id="questão-16" class="level2"><h2 class="anchored" data-anchor-id="questão-16">Questão 16</h2>
<p><strong>16 - Qual das seguintes afirmações é VERDADEIRA sobre gráficos de barra e boxplots?</strong></p>
<ul class="task-list">
<li><p><label><input type="checkbox" checked="">Gráficos de barra são mais adequados para comparar valores individuais entre diferentes grupos, enquanto boxplots são mais úteis para visualizar a distribuição dos dados dentro de um único grupo.</label></p></li>
<li><p><label><input type="checkbox">Boxplots são mais úteis para comparar valores individuais entre diferentes grupos, enquanto gráficos de barra são mais adequados para visualizar a distribuição dos dados dentro de um único grupo.</label></p></li>
<li><p><label><input type="checkbox">Gráficos de barra e boxplots são igualmente eficazes para comparar valores individuais entre diferentes grupos e visualizar a distribuição dos dados dentro de um único grupo.</label></p></li>
<li><p><label><input type="checkbox">Gráficos de barra e boxplots são adequados apenas para dados contínuos.</label></p></li>
<li><p><label><input type="checkbox">Boxplots são mais adequados para dados nominais, enquanto gráficos de barra são mais úteis para dados ordinais.</label></p></li>
</ul></section><section id="questão-17" class="level2"><h2 class="anchored" data-anchor-id="questão-17">Questão 17</h2>
<p><strong>17- Qual das seguintes afirmações é VERDADEIRA sobre por que o teste ANOVA é preferível ao teste t para comparar médias em mais de 2 grupos?</strong></p>
<ul>
<li><p>O teste t é mais apropriado para dados com distribuição normal, enquanto o ANOVA é mais robusto a desvios da normalidade.</p></li>
<li><p>O teste t pode ser utilizado para comparar diferentes variáveis de resposta, enquanto o ANOVA é limitado a um único fator de interesse.</p></li>
<li><p>O teste t é mais fácil de interpretar, enquanto a interpretação do ANOVA é mais complexa.</p></li>
<li><p>O teste t não requer homogeneidade de variâncias, enquanto o ANOVA exige que as variâncias entre os grupos sejam iguais.</p></li>
<li><p>O teste t é mais adequado para amostras grandes, enquanto o ANOVA é apropriado para amostras pequenas e grandes.</p></li>
<li><p><label><input type="checkbox" checked="">O teste t é limitado a comparar duas amostras, enquanto o ANOVA pode ser usado para comparar médias em três ou mais grupos.</label></p></li>
</ul></section><section id="questão-18" class="level2"><h2 class="anchored" data-anchor-id="questão-18">Questão 18</h2>
<p><strong>18- Qual das seguintes afirmações é VERDADEIRA sobre a relação entre tamanho de efeito e tamanho de amostra?</strong></p>
<ul>
<li><p>Quanto maior o tamanho da amostra, maior o tamanho do efeito.</p></li>
<li><p>O tamanho do efeito é independente do tamanho da amostra.</p></li>
<li><p><label><input type="checkbox" checked="">O tamanho do efeito é inversamente proporcional ao tamanho da amostra.</label></p></li>
<li><p>O tamanho do efeito é diretamente proporcional ao tamanho da amostra apenas em experimentos controlados.</p></li>
<li><p>O tamanho do efeito é diretamente proporcional ao tamanho da amostra apenas em experimentos observacionais.</p></li>
</ul></section><section id="questão-19" class="level2"><h2 class="anchored" data-anchor-id="questão-19">Questão 19</h2>
<p>19- Qual das seguintes afirmações é VERDADEIRA sobre o uso de intervalos de confiança para comparar diferenças entre um grupo em dois momentos diferentes no tempo?</p>
<ul>
<li><p><label><input type="checkbox">Os intervalos de confiança são usados apenas para descrever a precisão de uma estimativa, não para fazer inferências sobre a significância de uma diferença entre os momentos.</label></p></li>
<li><p>Intervalos de confiança são mais úteis para comparar grupos independentes do que grupos pareados.</p></li>
<li><p><label><input type="checkbox" checked="">Se o intervalo de confiança para a diferença entre os momentos incluir o valor zero, podemos concluir que não há diferença significativa entre os momentos.</label></p></li>
<li><p>O tamanho do intervalo de confiança é influenciado apenas pelo tamanho da amostra e não pela magnitude da diferença entre os momentos.</p></li>
<li><p>Intervalos de confiança não fornecem informações sobre a direção da diferença entre os momentos, apenas sobre a magnitude da diferença.</p></li>
</ul></section><section id="questão-20" class="level2"><h2 class="anchored" data-anchor-id="questão-20">Questão 20</h2>
<p>20- Era uma vez um guerreiro chamado Aragorn, que vivia em um reino ameaçado por um exército de Orcs liderados por um temível inimigo chamado Sauron. Aragorn sabia que a única maneira de vencer Sauron e salvar o reino era descobrir uma fraqueza em seu exército e explorá-la.</p>
<p>Aragorn sabia que Sauron era um grande consumidor de bebidas alcoólicas, então ele decidiu estudar os efeitos do álcool na saúde dos Orcs. Ele recrutou uma equipe de pesquisadores e coletou dados sobre a exposição dos Orcs ao álcool e a ocorrência de doenças em um determinado período.</p>
<p>Aragorn quer usar essas informações para desenvolver uma estratégia de batalha. Caso exista associações interessantes, ele ordenará que seus soldados atacassem os barris de cerveja e vinho dos Orcs durante a noite, com a esperança de reduzir sua capacidade de lutar no dia seguinte. Ele quer saber se os Orcs que não bebem alcool antes da batalha, não conseguem lutar.</p>
<p>O serviço de inteligência de Aragorn trouxe os dados A, B e C</p>
<p>A- Estudo Transversal da população de Orcs do império de Sauron feita com uso de espiões infiltrados</p>
<p>B- Estudo Caso Controle retrospectivo de dados de Orcs capturados em batalhas anteriores.</p>
<p>C- Estudo Longitudinal feito a partir de prisioneiros de guerra Orcs.</p>
<p>Olhando os dados das tabelas A,B,C e fazendo os calculos necessários das medidas de associação, é possível dizer que se Aragorn planejar sua estratégia de batalha baseado em ordenar que seus soldados ataquem os barris de cerveja e vinho dos Orcs durante a noite, com a esperança de reduzir sua capacidade de lutar no dia seguinte, será bem sucedido?</p>
<p>Justifique com base nos valores calculados e diga se os dados epidemiológicos podem ser valorizados como uma ferramenta valiosa na luta contra as ameaças à saúde do reino de Aragorn.</p>
<p><img src="images/clipboard-2597700249.png" class="img-fluid"></p>
<hr>
<section id="a-estudo-transversal" class="level3"><h3 class="anchored" data-anchor-id="a-estudo-transversal">A) Estudo transversal</h3>
<div class="cell">
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">est_transversal</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="fu">::</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span></span>
<span>  categoria <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Orcs Bebem"</span>, <span class="st">"Orcs Abstemios"</span><span class="op">)</span>,</span>
<span>  nao_lutam <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">200</span>, <span class="fl">1500</span><span class="op">)</span>,</span>
<span>  lutam <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">300</span>, <span class="fl">3500</span><span class="op">)</span></span>
<span><span class="op">)</span> <span class="op">|&gt;</span>   <span class="fu">tibble</span><span class="fu">::</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/rownames.html">column_to_rownames</a></span><span class="op">(</span><span class="st">"categoria"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">est_transversal</span> <span class="op">|&gt;</span> <span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">nao_lutam</th>
<th style="text-align: right;">lutam</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Orcs Bebem</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">300</td>
</tr>
<tr class="even">
<td style="text-align: left;">Orcs Abstemios</td>
<td style="text-align: right;">1500</td>
<td style="text-align: right;">3500</td>
</tr>
</tbody>
</table>
</div>
</div>
</section><section id="b-estudo-caso-controle" class="level3"><h3 class="anchored" data-anchor-id="b-estudo-caso-controle">B) Estudo Caso-controle</h3>
<div class="cell">
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">est_cc</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="fu">::</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span></span>
<span>  categoria <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Orcs Bebem"</span>, <span class="st">"Orcs Abstemios"</span><span class="op">)</span>,</span>
<span>  nao_lutam <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">100</span>, <span class="fl">50</span><span class="op">)</span>,</span>
<span>  lutam <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">400</span>, <span class="fl">450</span><span class="op">)</span></span>
<span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu">tibble</span><span class="fu">::</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/rownames.html">column_to_rownames</a></span><span class="op">(</span><span class="st">"categoria"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">est_cc</span> <span class="op">|&gt;</span> <span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">nao_lutam</th>
<th style="text-align: right;">lutam</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Orcs Bebem</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">400</td>
</tr>
<tr class="even">
<td style="text-align: left;">Orcs Abstemios</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">450</td>
</tr>
</tbody>
</table>
</div>
</div>
</section><section id="c-coorte" class="level3"><h3 class="anchored" data-anchor-id="c-coorte">C) Coorte</h3>
<div class="cell">
<details open="" class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">est_coorte</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="fu">::</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span></span>
<span>  categoria <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Orcs Bebem"</span>, <span class="st">"Orcs Abstemios"</span><span class="op">)</span>,</span>
<span>  nao_lutam <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">200</span>, <span class="fl">300</span><span class="op">)</span>,</span>
<span>  lutam <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">800</span>, <span class="fl">1700</span><span class="op">)</span></span>
<span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu">tibble</span><span class="fu">::</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/rownames.html">column_to_rownames</a></span><span class="op">(</span><span class="st">"categoria"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">est_coorte</span> <span class="op">|&gt;</span> <span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">nao_lutam</th>
<th style="text-align: right;">lutam</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Orcs Bebem</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">800</td>
</tr>
<tr class="even">
<td style="text-align: left;">Orcs Abstemios</td>
<td style="text-align: right;">300</td>
<td style="text-align: right;">1700</td>
</tr>
</tbody>
</table>
</div>
</div>
</section><section id="resposta" class="level3"><h3 class="anchored" data-anchor-id="resposta">Resposta</h3>
<p><strong>É possível dizer que se Aragorn planejar sua estratégia de batalha baseado em ordenar que seus soldados ataquem os barris de cerveja e vinho dos Orcs durante a noite, com a esperança de reduzir sua capacidade de lutar no dia seguinte, será bem sucedido?</strong></p>
<p>Será que a bebida AJUDA os orcs a lutarem melhor?</p>
<p>Neste caso, consideramos que a exposição é beber ou não, e o desfecho é lutar ou não lutar.</p>
<p>Exposto (Orcs Bebem) - Desfecho: lutam | Exposto (Orcs Bebem) - Desfecho: não lutam ________________________________________________________________________________ Não-exposto (Orcs abstêmios) - Desfecho: lutam | Não-exposto (Orcs não bebem) - Desfecho: não lutam</p>
<p>Com os resultados do estudo transversal, podemos calcular a razão de prevalências:</p>
<ul>
<li><p>Prevalência de Orcs que não lutam, dentre os expostos (beberam) = 200 / 200+300 = 0.4</p></li>
<li><p>Prevalência de Orcs que não lutam, dentre os não-expostos (abstêmios) = 1500 / 1500+3500 = 0.3</p></li>
<li><p>Razão de prevalências: 0.4/0.3 = 1.33</p></li>
</ul>
<p>Esse resultado aponta que existe associação entre desfecho “não lutar” e a exposição ao álcool. A interpretação dos resultados sugere que existe mais Orcs que não lutam quando são expostos (bebem).</p>
<hr>
<p>Com os resultados do estudo caso-controle, podemos calcular a razão de chances (<em>odds-ratio</em>).</p>
<p>O que eu espero? Que Orcs que bebem, lutem. E que os Orcs que não bebem, não lutem.</p>
<ul>
<li><p>Chance de acontecer o que eu espero: orcs_bebem_lutam * orcs_abstemios_nao_lutam = 400 * 50 = 20000</p></li>
<li><p>Chance de acontecer o que eu NÃO espero: orcs_bebem_nao_lutam * orcs_abstemios_lutam = 100 * 450 = 45000</p></li>
<li><p>Razão de chances: 20000/45000 = 20/45 = 0.44</p></li>
</ul>
<p>Interpretação: existe uma associação - não espero. <strong>MELHORAR ISSO</strong></p>
<p>Entendo que existe uma chance maior de orcs que bebem não lutarem, e orcs abstêmios lutarem.</p>
<hr>
<p>Com os resultados do Coorte, podemos calcular a razão de incidência (risco relativo):</p>
<ul>
<li><p>Incidência dos orcs que “NÃO LUTAM” dentre os expostos: 200/200+800 = 0.2</p></li>
<li><p>Incidência dos orcs que “NÃO LUTAM” dentre os não-expostos: 300/300+1700 = 0.15</p></li>
<li><p>Razão de incidência = 0.2 / 0.15 = 1.333</p></li>
<li><p>A interpretação é: existem mais Orcs que não lutam quando são expostos ao alcool.</p></li>
</ul>
<hr>
<p>Respondendo a pergunta: <strong>Se Aragorn planejar sua estratégia de batalha baseado em ordenar que seus soldados ataquem os barris de cerveja e vinho dos Orcs durante a noite, com a esperança de reduzir sua capacidade de lutar no dia seguinte, será bem sucedido?</strong></p>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Pensar!</p>
</div>
</div>
</div>
<hr></section></section></section><section id="links-que-podem-ser-úteis" class="level1"><h1>Links que podem ser úteis:</h1>
<ul>
<li><p>Apostila sobre bioestatística: https://www.fcav.unesp.br/Home/departamentos/cienciasexatas/alanrodrigopanosso/apostila_bioestatistica_2019.pdf</p></li>
<li><p>Apostila curta sobre intervalo de confiança: https://midia.atp.usp.br/plc/plc0503/impressos/plc0503_04.pdf</p></li>
<li><p>Interpretação do boxplot: https://fernandafperes.com.br/blog/interpretacao-boxplot/</p></li>
</ul></section></main><!-- /main column --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>